### ISSUE TITLE
I probably miss something, but many of the autocompletes don't work for me

### ISSUE THREAD

**Issue by oriSomething** [wagenet/ember.d.ts#1]
for example `Ember.computed.*`. it doesn't autocomplete. but when i do something like this `var x = new Ember.computed();` than i get the desired autocomplete of `Ember.computed`.
i'm not sure if i did something wrong or the fact that in the definition file i see `computed` as `class`.

**Comment by wagenet** [comment]
@oriSomething Sorry for missing this issue for so long. I'm not an expert in this area so it's definitely possible I'm doing something wrong. There are also a few unusual things in Ember itself that we might need to add some special casings for.

**Comment by oriSomething** [comment]
Closing this issue because it doesn't seems relevant anymore
